root: true
parser: '@typescript-eslint/parser'
env: { browser: false, es6: false, node: true }
plugins:
  - 'no-loops'
  - 'prettier'
  - '@typescript-eslint'
extends:
  - './strongloop.json'
  - 'eslint:recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
rules:
  func-name-matching: 2
  prettier/prettier: 2
  no-loops/no-loops: 2
  no-await-in-loop: 2
  no-return-await: 2
  prefer-spread: 1
  prefer-const: 2
  no-var: 2
  max-len: [1, { code: 100 }]
  object-shorthand: [2, always]
  id-denylist: [2, err, e, cb, callback]
  lines-between-class-members: [1, never]
  no-param-reassign: [2, { props: false }]
  newline-per-chained-call: [2, { ignoreChainWithDepth: 5 }]
  func-style: [2, declaration, { allowArrowFunctions: true }]
  consistent-return: [1, { treatUndefinedAsUnspecified: true }]
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': [2, allowArgumentsExplicitlyTypedAsAny: true]
